name: Prisma-scan

on:
  push:
    branches: [ "main"]
  pull_request:
    branches: ["main"]

permissions:
  id-token: write
  contents: read
  pull-requests: write

env:
  TF_LOG: INFO
  worfklow_dispatch:


jobs:
  codescan:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout tools repo
        uses: actions/checkout@v3

      - name: Run Bridgecrew
        id: Bridgecrew
        uses: bridgecrewio/bridgecrew-actions@master
        env:
          PRISMA_API_URL: https://api2.prismacloud.io
        with:
          api-key: $ {{ secrets.BC_API_KEY }}
          check: 'HIGH,CRITICA'
  
